# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Danger of Carnivore & Keto Diets
email: quintus.sertorius.blue@gmail.com
description: >-
  While Carnivore and Keto are potent elimination diet, there might be serious side effects to consider.
baseurl: ""
url: "https://notjustmeat.co"
twitter_username: BlueSertorius
github_username:  BlueSertorius

markdown: kramdown

collections:
  peoples:
    output: true
    permalink: /:collection/:name/
  archives:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: "wiki/pages"
      type: "pages"
    values:
      layout: wiki-page
      permalink: /wiki/:basename/
      current_tab: /wiki/
      categories: wiki
  -
    scope:
      path: "_archives"
    values:
      layout: archive-page
      current_tab: /archives/
      categories: archives
      is_article: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bin
